### ISSUE TITLE
{get,set}AttributeNode is not a function: not working with @mozilla/readability@0.6.0

### ISSUE THREAD

**Issue by M4RC3L05** [b-fuze/deno-dom#189]
Looks like the latest update on @mozilla/readability, v0.6.0 broke with following error:
```
TypeError: replacement.setAttributeNode is not a function
                at Readability._setNodeTag (file:///.../node_modules/.deno/@mozilla+readability@0.6.0/node_modules/@mozilla/readability/Readability.js:770:19)
                at Readability._grabArticle (file:///.../node_modules/.deno/@mozilla+readability@0.6.0/node_modules/@mozilla/readability/Readability.js:1201:25)
                at Readability.parse (file:///.../node_modules/.deno/@mozilla+readability@0.6.0/node_modules/@mozilla/readability/Readability.js:2747:31)
                ...
```

It does work with @mozilla/readability v0.5.0.

Code example
```ts
const pageContent = await pageContentResponse.text();
const dom = new DOMParser().parseFromString(pageContent, "text/html");
const parsed = new Readability(dom).parse();
```

Running using deno v2.2.5 and @b-fuze/deno-dom@0.1.49.

**Comment by M4RC3L05** [comment]
@KonghaYao thx, that seens to work
